use std::fmt::Display;

use crate::src_loc::SrcLoc;

#[derive(Debug, Clone)]
pub struct Token {
    pub loc: SrcLoc,
    pub kind: TokenKind,
}
#[derive(PartialEq, Eq, Debug, Clone)]
pub enum TokenKind {
    With,
    LeftBrace,
    RightBrace,
    Equal,
    Coma,
    Plus,
    Minus,
    Slash,
    End,
    Star,
    Caret,
    Of,
    Do,
    Dot,
    Lesser,
    Greater,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Pipe,
    Number(u64),
    Semi,
    Colon,
    Fun,
    Char,
    Print,
    Borrow,
    Ident(String),
    Int,
    Bool,
    String,
    StringLiteral(String),
    Ref,
    Static,
    Let,
    Mut,
    Imm,
    Case,
    In,
    Panic,
    For,
    Arrow,
    ThickArrow,
    DoubleEqual,
    True,
    False,
    Error,
    Region,
    While,
    At,
    Type,
    As,
    AddrOf,
    Import,
    Eof,
    And,
    Return,
}

impl Display for TokenKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let txt = match self {
            Self::At => "@",
            Self::Semi => ";",
            Self::LeftBrace => "{",
            Self::RightBrace => "}",
            Self::Coma => ",",
            Self::Arrow => "->",
            Self::ThickArrow => "=>",
            Self::Bool => "bool",
            Self::False => "false",
            Self::Minus => "-",
            Self::True => "true",
            Self::Star => "*",
            Self::Plus => "+",
            Self::Equal => "=",
            Self::Pipe => "|",
            Self::Of => "of",
            Self::Do => "do",
            Self::Dot => ".",
            Self::AddrOf => "addr_of",
            Self::DoubleEqual => "==",
            Self::Lesser => "<",
            Self::Greater => ">",
            Self::StringLiteral(literal) => {
                f.write_str("\"")?;
                f.write_str(literal)?;
                return f.write_str("\"");
            }
            Self::While => "while",
            Self::LeftParen => "(",
            Self::RightParen => ")",
            Self::LeftBracket => "[",
            Self::RightBracket => "]",
            Self::Caret => "^",
            Self::Panic => "panic",
            Self::For => "for",
            Self::Static => "static",
            Self::Colon => ":",
            Self::Slash => "/",
            Self::Char => "char",
            Self::Print => "print",
            Self::Fun => "fun",
            Self::Borrow => "borrow",
            Self::In => "in",
            Self::Int => "int",
            Self::String => "string",
            Self::Imm => "imm",
            Self::Ref => "ref",
            Self::Number(number) => return write!(f, "{number}"),
            Self::Mut => "mut",
            Self::Let => "let",
            Self::Case => "case",
            Self::End => "end",
            Self::Ident(name) => name,
            Self::Error => "{error}",
            Self::Region => "region",
            Self::Import => "import",
            Self::Type => "type",
            Self::Eof => "EOF",
            Self::With => "with",
            Self::As => "as",
            Self::And => "and",
            Self::Return => "return"
        };
        f.write_str(txt)
    }
}
